### ISSUE TITLE
CPLEX LP file processing error

### ISSUE THREAD

**Issue by matteodefelice** [PyPSA/PyPSA#26]
Hi, on Mac Os X I have installed the latest GitHub version of PyPSA. I am using conda-based Python 3 with all the latest libraries. 
I have tried to run a few examples but most of them does not work. 
Here an example:
```
(py36) $ python unit-commitment.py 
INFO:pypsa.pf:Slack bus for sub-network 0 is bus
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
INFO:pypsa.opf:Solving model using glpk
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 616, solve
	Solver (glpk) returned non-zero return code (1)
ERROR:pyomo.opt:Solver (glpk) returned non-zero return code (1)
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 621, solve
	Solver log:
	GLPSOL: GLPK LP/MIP Solver, v4.63
	Parameter(s) specified in the command line:
	 --write /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmp8t3bfxle.glpk.raw
	 --wglp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpym96u0i3.glpk.glp
	 --cpxlp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp
	Reading problem data from '/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp'...
	/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp:13: constraints section missing
	CPLEX LP file processing error
ERROR:pyomo.opt:Solver log:
GLPSOL: GLPK LP/MIP Solver, v4.63
Parameter(s) specified in the command line:
 --write /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmp8t3bfxle.glpk.raw
 --wglp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpym96u0i3.glpk.glp
 --cpxlp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp
Reading problem data from '/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp'...
/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpyg7mrrpa.pyomo.lp:13: constraints section missing
CPLEX LP file processing error

Traceback (most recent call last):
  File "unit-commitment.py", line 36, in <module>
    nu.lopf(nu.snapshots)
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pypsa-0.11.0-py3.6.egg/pypsa/opf.py", line 1452, in network_lopf
    return network_lopf_solve(network, snapshots, formulation=formulation, solver_options=solver_options, keep_files=keep_files, free_memory=free_memory)
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pypsa-0.11.0-py3.6.egg/pypsa/opf.py", line 1377, in network_lopf_solve
    network.results = network.opt.solve(*args, suffixes=["dual"], keepfiles=keep_files, options=solver_options) 
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pyomo/opt/base/solvers.py", line 623, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (glpk) did not exit normally
```
GLPK has been installed with MacPorts.

**Comment by nworbmot** [comment]
Hi Matteo, these problems are usually caused by the Pyomo interface to GLPK, not PyPSA. It's working fine for me with Pyomo 5.3 and GLPK 4.51. Double-check you have the latest version of Pyomo installed, otherwise you could try downgrading the version of GLPK or use the open source CBC solver (which is faster anyway). Once you've installed it, pass network.lopf the argument solver_name="cbc".

**Comment by matteodefelice** [comment]
Thanks for the quick reply. Pyomo's version is 5.3 and I downgrade GLPK to 4.51 (re-installing from source instead than using MacPorts). Unfortunately, I still get the same error, it just changed the GLPK version number
```
INFO:pypsa.pf:Slack bus for sub-network 0 is bus
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
INFO:pypsa.opf:Solving model using glpk
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 616, solve
	Solver (glpk) returned non-zero return code (1)
ERROR:pyomo.opt:Solver (glpk) returned non-zero return code (1)
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 621, solve
	Solver log:
	GLPSOL: GLPK LP/MIP Solver, v4.51
	Parameter(s) specified in the command line:
	 --write /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpkidtquhi.glpk.raw
	 --wglp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmphh25e53w.glpk.glp
	 --cpxlp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp
	Reading problem data from `/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp'...
	/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp:13: constraints section missing
	CPLEX LP file processing error
ERROR:pyomo.opt:Solver log:
GLPSOL: GLPK LP/MIP Solver, v4.51
Parameter(s) specified in the command line:
 --write /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpkidtquhi.glpk.raw
 --wglp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmphh25e53w.glpk.glp
 --cpxlp /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp
Reading problem data from `/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp'...
/var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp:13: constraints section missing
CPLEX LP file processing error

Traceback (most recent call last):
  File "unit-commitment.py", line 36, in <module>
    nu.lopf(nu.snapshots)
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pypsa-0.11.0-py3.6.egg/pypsa/opf.py", line 1452, in network_lopf
    return network_lopf_solve(network, snapshots, formulation=formulation, solver_options=solver_options, keep_files=keep_files, free_memory=free_memory)
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pypsa-0.11.0-py3.6.egg/pypsa/opf.py", line 1377, in network_lopf_solve
    network.results = network.opt.solve(*args, suffixes=["dual"], keepfiles=keep_files, options=solver_options) 
  File "/Users/matteodefelice/miniconda2/envs/py36/lib/python3.6/site-packages/pyomo/opt/base/solvers.py", line 623, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (glpk) did not exit normally
```

I will try with `cbc`

**Comment by nworbmot** [comment]
Glad it works with cbc! This isn't the first time there have been Pyomo-GLPK problems. If you can be bothered, try looking in the LP file /var/folders/x6/qsstd0cd44x3jhbrbfxkv_7w0000gn/T/tmpmhywlo45.pyomo.lp and see how it compares to mine:

\* Source Pyomo model name=Linear Optimal Power Flow *\

min 
x21:
+20 x1
+20 x2
+20 x3
+20 x4
+70 x5
+70 x6
+70 x7
+70 x8

s.t.

c_u_x22_:
-1 x1
+3000 x9
<= 0

c_u_x23_:
+3000 x10
-1 x2
<= 0

c_u_x24_:
+3000 x11
-1 x3
<= 0

c_u_x25_:
+3000 x12
-1 x4
<= 0

c_u_x26_:
+100 x13
-1 x5
<= 0

c_u_x27_:
+100 x14
-1 x6
<= 0

c_u_x28_:
+100 x15
-1 x7
<= 0

c_u_x29_:
+100 x16
-1 x8
<= 0

c_l_x30_:
-1 x1
+10000 x9
>= 0

c_l_x31_:
+10000 x10
-1 x2
>= 0

c_l_x32_:
+10000 x11
-1 x3
>= 0

c_l_x33_:
+10000 x12
-1 x4
>= 0

c_l_x34_:
+1000 x13
-1 x5
>= 0

c_l_x35_:
+1000 x14
-1 x6
>= 0

c_l_x36_:
+1000 x15
-1 x7
>= 0

c_l_x37_:
+1000 x16
-1 x8
>= 0

c_e_x38_:
+1 x17
= 0

c_e_x39_:
+1 x18
= 0

c_e_x40_:
+1 x19
= 0

c_e_x41_:
+1 x20
= 0

c_e_x42_:
+1 x1
+1 x5
= 4000

c_e_x43_:
+1 x2
+1 x6
= 6000

c_e_x44_:
+1 x3
+1 x7
= 5000

c_e_x45_:
+1 x4
+1 x8
= 800

c_e_ONE_VAR_CONSTANT: 
ONE_VAR_CONSTANT = 1.0

bounds
    -inf <= x1 <= +inf
    -inf <= x2 <= +inf
    -inf <= x3 <= +inf
    -inf <= x4 <= +inf
    -inf <= x5 <= +inf
    -inf <= x6 <= +inf
    -inf <= x7 <= +inf
    -inf <= x8 <= +inf
   0 <= x9 <= 1
   0 <= x10 <= 1
   0 <= x11 <= 1
   0 <= x12 <= 1
   0 <= x13 <= 1
   0 <= x14 <= 1
   0 <= x15 <= 1
   0 <= x16 <= 1
    -inf <= x17 <= +inf
    -inf <= x18 <= +inf
    -inf <= x19 <= +inf
    -inf <= x20 <= +inf
binary
  x9
  x10
  x11
  x12
  x13
  x14
  x15
  x16
end

**Comment by matteodefelice** [comment]
I see one difference: I have a `nan` at the beginning:

```\* Source Pyomo model name=Linear Optimal Power Flow *\

min 
x21:
+20 x1
+20 x2
+20 x3
+20 x4
+70 x5
+70 x6
+70 x7
+70 x8
+nan ONE_VAR_CONSTANT

s.t.

c_u_x22_:
-1 x1
+3000 x9
<= 0

c_u_x23_:
+3000 x10
-1 x2
<= 0

c_u_x24_:
+3000 x11
-1 x3
<= 0

c_u_x25_:
+3000 x12
-1 x4
<= 0

c_u_x26_:
+100 x13
-1 x5
<= 0

c_u_x27_:
+100 x14
-1 x6
<= 0

c_u_x28_:
+100 x15
-1 x7
<= 0

c_u_x29_:
+100 x16
-1 x8
<= 0

c_l_x30_:
-1 x1
+10000 x9
>= 0

c_l_x31_:
+10000 x10
-1 x2
>= 0

c_l_x32_:
+10000 x11
-1 x3
>= 0

c_l_x33_:
+10000 x12
-1 x4
>= 0

c_l_x34_:
+1000 x13
-1 x5
>= 0

c_l_x35_:
+1000 x14
-1 x6
>= 0

c_l_x36_:
+1000 x15
-1 x7
>= 0

c_l_x37_:
+1000 x16
-1 x8
>= 0

c_e_x38_:
+1 x17
= 0

c_e_x39_:
+1 x18
= 0

c_e_x40_:
+1 x19
= 0

c_e_x41_:
+1 x20
= 0

c_e_x42_:
+1 x1
+1 x5
= 4000

c_e_x43_:
+1 x2
+1 x6
= 6000

c_e_x44_:
+1 x3
+1 x7
= 5000

c_e_x45_:
+1 x4
+1 x8
= 800

c_e_ONE_VAR_CONSTANT: 
ONE_VAR_CONSTANT = 1.0

bounds
    -inf <= x1 <= +inf
    -inf <= x2 <= +inf
    -inf <= x3 <= +inf
    -inf <= x4 <= +inf
    -inf <= x5 <= +inf
    -inf <= x6 <= +inf
    -inf <= x7 <= +inf
    -inf <= x8 <= +inf
   0 <= x9 <= 1
   0 <= x10 <= 1
   0 <= x11 <= 1
   0 <= x12 <= 1
   0 <= x13 <= 1
   0 <= x14 <= 1
   0 <= x15 <= 1
   0 <= x16 <= 1
    -inf <= x17 <= +inf
    -inf <= x18 <= +inf
    -inf <= x19 <= +inf
    -inf <= x20 <= +inf
binary
  x9
  x10
  x11
  x12
  x13
  x14
  x15
  x16
end
```

**Comment by nworbmot** [comment]
Hmm, this is confusing. It's definitely a Pyomo-GLPK problem. If you look at the Pyomo code https://github.com/Pyomo/pyomo/blob/master/pyomo/solvers/plugins/solvers/GLPK.py it handles the various GLPK versions differently, but I don't know why it's giving different output now you've downgraded GLPK. Perhaps Pyomo's still picking up the newer GLPK version when it checks the version, I don't know. CBC has solved your problem, but to progress further with GLPK one would have to isolate the Pyomo bug and either fix it or make a bug report. Or wait until someone else fixes it...

**Comment by matteodefelice** [comment]
Ok, let's keep this issue open, I will try to see what happens on my ubuntu machine (perhaps I can try to downgrade `pyomo` instead)...

**Comment by coroa** [comment]
pandas 0.21.0 changes sum() behavior so that the result of applying sum over an empty DataFrame is NaN (see pandas-dev/pandas#9422 for context), which led to nans appearing in the objective, which glpk did not handle well, while cbc and gurobi were dropping them silently.
