### ISSUE TITLE
AC-DC-lopf examples fails with v0.18.0 installation of PyPSA

### ISSUE THREAD

**Issue by fwitte** [PyPSA/PyPSA#296]
## Describe the Bug

With both, the installation through conda as well as the version v0.18.0 checked out through git the ac-dc-lopf example fails on my machine when solving with the following error.

**This is not the case with the current state of the master branch,** so I do not know if it has already been fixed or is an actual issue (I couldn't find any issue mentioning this problem). If it isn't an issue, we can just close it and I'll stick working with the current master branch version.

I am working with

- python 3.8.11
- pypsa 0.18.0/master
- pyomo 6.1.2
- glpk 5.0

## Error Message

```
Traceback (most recent call last):
  File "ac-dc-lopf.py", line 37, in <module>
    network.lopf()
  File "c:\users\witt_fa\documents\github\egon\pypsa\pypsa\components.py", line 648, in lopf
    return network_lopf(self, **args)
  File "c:\users\witt_fa\documents\github\egon\pypsa\pypsa\opf.py", line 1653, in network_lopf
    network_lopf_build_model(network, snapshots, skip_pre=skip_pre,
  File "c:\users\witt_fa\documents\github\egon\pypsa\pypsa\opf.py", line 1451, in network_lopf_build_model
    define_generator_variables_constraints(network,snapshots)
  File "c:\users\witt_fa\documents\github\egon\pypsa\pypsa\opf.py", line 110, in define_generator_variables_constraints
    l_constraint(network.model, "generator_p_lower", gen_p_lower,
  File "c:\users\witt_fa\documents\github\egon\pypsa\pypsa\opt.py", line 204, in l_constraint
    v._data[i]._equality = False
AttributeError: '_GeneralConstraintData' object has no attribute '_equality'
```

**Comment by FabianHofmann** [comment]
@fwitte thanks for reporting! Yes I also saw a similar bug when compiling the doc. we have to look into it. The reason is that the new pyomo version does not support the hidden attributes that we use anymore...

**Comment by FabianHofmann** [comment]
reopen if issue persists
