### ISSUE TITLE
ERROR IN RUNNING EXAMPLE

### ISSUE THREAD

**Issue by VladTempest** [PyPSA/PyPSA#46]
I am just install Python 3.7, I did all what was written in "Installation". But when I'm trying to runn Example from Quick start - I get this message:
 
Traceback (most recent call last):
  File "C:/Users/Me_OnlyME/AppData/Local/Programs/Python/Python37-32/examples/minimal_example_pf.py", line 8, in <module>
    import pypsa
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\pypsa\__init__.py", line 28, in <module>
    from . import components, descriptors
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\pypsa\components.py", line 63, in <module>
    from .contingency import (calculate_BODF, network_lpf_contingency,
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\pypsa\contingency.py", line 42, in <module>
    from .opt import l_constraint
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\pypsa\opt.py", line 41, in <module>
    from pyomo.environ import Constraint, Objective, Var, ComponentUID
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\environ\__init__.py", line 89, in <module>
    _import_packages()
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\environ\__init__.py", line 59, in _import_packages
    _do_import(pname)
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\environ\__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\pysp\__init__.py", line 25, in <module>
    import pyomo.pysp.scenariotree
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\pysp\scenariotree\__init__.py", line 18, in <module>
    import pyomo.pysp.scenariotree.manager
  File "C:\Users\Me_OnlyME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 969
    async=False,
        ^
SyntaxError: invalid syntax

Process finished with exit code 1

Can you help me? What should I do to fix this problem...

**Comment by coroa** [comment]
Hi,

your problem seems to be related to the installation of pyomo, please make sure you can use it to solve simple problems, like the one at
https://pyomo.readthedocs.io/en/latest/pyomo_overview/simple_examples.html#a-simple-concrete-pyomo-model

i.e. check that the following code works and finds the minimum 2/3:
```python
from pyomo.environ import *
model = ConcreteModel()
model.x = Var([1,2], domain=NonNegativeReals)
model.OBJ = Objective(expr = 2*model.x[1] + 3*model.x[2])
model.Constraint1 = Constraint(expr = 3*model.x[1] + 4*model.x[2] >= 1)

opt = SolverFactory('glpk')
results = opt.solve(model)
print(results)
```

If not, look for troubleshooting instructions in their [manual](https://pyomo.readthedocs.io/en/latest/) and eventually seek help from them.

Best,
Jonas
