### ISSUE TITLE
Warmstart error when using Xpress as the solver

### ISSUE THREAD

**Issue by PeterKlein11** [PyPSA/PyPSA#541]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

When using Xpress as the solver there is an error in run_and_read_xpress, when there is no existing basis function. 

## Error Message

```
Reading Problem pypsa-problem-ki6fpit6
Problem Statistics
      122767 (      0 spare) rows
       58823 (      0 spare) structural columns
      248508 (      0 spare) non-zero elements
Global Statistics
           0 entities        0 sets        0 set members
Traceback (most recent call last):
  File "/home/pklein/GitHub/pypsa-eur2/.snakemake/shadow/tmppqqh_5p7/.snakemake/scripts/[tmp153y13_b.solve_network.py](http://tmp153y13_b.solve_network.py/)", line 370, in <module>
    n = solve_network(n, snakemake.config, opts, solver_dir=tmpdir,
  File "/home/pklein/GitHub/pypsa-eur2/.snakemake/shadow/tmppqqh_5p7/.snakemake/scripts/[tmp153y13_b.solve_network.py](http://tmp153y13_b.solve_network.py/)", line 345, in solve_network
    ilopf(n, solver_name=solver_name, solver_options=solver_options,
  File "/home/pklein/anaconda3/envs/pypsa-eur-2/lib/python3.10/site-packages/pypsa/linopf.py", line 1606, in ilopf
    status, termination_condition = network_lopf(n, snapshots, **kwargs)
  File "/home/pklein/anaconda3/envs/pypsa-eur-2/lib/python3.10/site-packages/pypsa/linopf.py", line 1462, in network_lopf
    res = solve(
  File "/home/pklein/anaconda3/envs/pypsa-eur-2/lib/python3.10/site-packages/pypsa/linopt.py", line 1158, in run_and_read_xpress
    m.readbasis(warmstart)
TypeError: argument 1 must be str, not bool
```

**Comment by fneum** [comment]
closed via cb363ab610e609806c85f054370f3b9792c94e77
