### ISSUE TITLE
Cannot convert non-finite values (NA or inf) to integer

### ISSUE THREAD

**Issue by davide-f** [PyPSA/PyPSA#637]
## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

When running pypsa-earth on LT (Lithuania), a NA error appears using PyPSA when loading files from netCDF.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

``` bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp9bknsrmp.add_extra_components.py", line 242, in <module>
    n = pypsa.Network(snakemake.input.network)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/components.py", line 341, in __init__
    self.import_from_netcdf(import_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 644, in import_from_netcdf
    _import_from_importer(network, importer, basename=basename, skip_time=skip_time)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 794, in _import_from_importer
    import_components_from_dataframe(network, df, component)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 860, in import_components_from_dataframe
    dataframe[k] = dataframe[k].astype(static_attrs.at[k, "typ"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by euronion** [comment]
Could be network specific. Can you share the network?

**Comment by davide-f** [comment]
Sure.
I could share elec_s (the previous network), clustered one (the one leading to this error) and the config.
I agree that is network specific; not sure if it is generated by an unexpected behavior in the clustered triggered by the specific network.
I send you the files as I get access to the computer

**Comment by euronion** [comment]
The network which throws this error upon loading would suffice for now. You could also check yourself: Load it using `xarray` instead of the PyPSA function and check which entries are `nan` or `inf`.

**Comment by davide-f** [comment]
I uploaded the files here: https://drive.google.com/drive/folders/1D_Tw-itu9vV478lnO1mOSVcjg__8qfqq?usp=share_link

**Comment by davide-f** [comment]
The issue seems related to build_year for a link that while being 0 after simplify_network, becomes NaN after the clustering.
The link is also the only link available in the network.
