### ISSUE TITLE
Bug(?) when adding constraints to Links

### ISSUE THREAD

**Issue by andrevlisboa** [PyPSA/PyPSA#757]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest

## Describe the Bug

I think there might me an error when post-processing the network model, when multiple Links have additional constraints. When it is just one, it works fine.

As an example:

Looking at a modelling like:
```
|main_bus|-----|bus|--link--|store|
```
And adding the following constraint:
```
link_power = network_model.variables["Link-p"].sel({"Link": link["name"]})

lhs = link_power.sum()
rhs = 100 (for example)
network_model.add_constraints(lhs == rhs, name="constraint1")


link_power = network_model.variables["Link-p"].sel({"Link": link["name"]})

lhs = link_power.sum()
rhs = 100 (for example)
network_model.add_constraints(lhs == rhs, name="constraint1")

```
## Error Message

Xarray will raise an error in post-processing on merge data

Note: The optimization is done correctly, however the post processing raises an error

**Comment by fneum** [comment]
What is the error message? Do you have an example how we can reproduce the behaviour?

**Comment by FabianHofmann** [comment]
Hey,

the code worked for me. Perhaps you have to update Linopy?


Here are some improvements:

import pypsa
import xarray as xr
import pandas as pd

SNAPSHOTS = pd.date_range("2023-01-01 09:00", "2023-01-01 19:00", freq="H")

LOAD = {
     "name": "load_1",
     "profile": pd.Series(
         [40, 70, 60, 50, 10, 20, 40, 50, 50, 40, 40], index=SNAPSHOTS
     ),
}

GENERATORS = [
     {"name": "gas_1", "p_nom": 100, "p_min": 0, "marginal_cost": 10},
     {"name": "gas_2", "p_nom": 100, "p_min": 50, "marginal_cost": 5},
]


############
network = pypsa.Network()

network.set_snapshots(SNAPSHOTS)

main_bus = "bus_grid"
network.add("Bus", name=main_bus)

for gen in GENERATORS:
     network.add(
         "Generator",
         name=gen["name"],
         bus=main_bus,
         committable=True,
         p_nom=gen["p_nom"],
         marginal_cost=gen["marginal_cost"],
     )
network.generators["p_min"] = [gen["p_min"] for gen in GENERATORS]

network.add("Load", name=LOAD["name"], bus=main_bus, p_set=LOAD["profile"])

network_model = network.optimize.create_model()

generator_power = network_model.variables["Generator-p"]
generator_status = network_model.variables["Generator-status"]
p_min = xr.DataArray(network.generators.p_min, dims=["Generator-com"])
lhs = generator_power - generator_status * p_min
rhs = 0
network_model.add_constraints(lhs >= rhs, name="Generator-p-min")


network.optimize.solve_model(solver_name="highs")

**Comment by andrevlisboa** [comment]
I have the following version:
pypsa==0.25.2
linopy==0.3.1
xarray==2023.10.1

**Comment by rizky-r-lab** [comment]
Same with me,
i have error in my PopOS, while in my windows 11 running fine

**Comment by FabianHofmann** [comment]
hey @rizky-r-lab, could you confirm you are one the later master branch in pypsa?

**Comment by rizky-r-lab** [comment]
hey @FabianHofmann , i install using conda. However if i install using latest master branch, there are several package installed and the error disappear.
FYI, the problems is in highs solver. Because if i using gurobi, there are no problem

**Comment by Tooblippe** [comment]
Hi, We are having a similar issue when we add these variables and constraints. The solver solves, but it also seems in post processing to trough the error below.

`        #Obtain variables and attributes for link1 & store1
        Link1_MWh = m.variables["Link-p"].sel(Link="Lk95_(B2_HCB-B_Songo)") # This is the electricity link from water link
        Link1_p_nom = network.links.at["Lk95_(B2_HCB-B_Songo)", "p_nom"]  # Capacity of electricity link from turbine
        Store1_level = m.variables["Store-e"].sel(Store="HCB-Res") # This is store
        Store1_e_nom = network.stores.at["HCB-Res", "e_nom"]  # Total storage
        min_turbine1_eff = network.stores.at["HCB-Res", "min_turbine_eff"] # This is a new attribute to be added to csv file
        delta_turbine1_eff = 1 - min_turbine1_eff # Define Efficiency Range

        #Obtain variables and attributes for link2 & store2
        Link2_MWh = m.variables["Link-p"].sel(Link="Lk114_(B3_MNK-B_MNK)") # This is the electricity link from water link
        Link2_p_nom = network.links.at["Lk114_(B3_MNK-B_MNK)", "p_nom"]  # Capacity of electricity link from turbine
        Store2_level = m.variables["Store-e"].sel(Store="MNK-Res") # This is store
        Store2_e_nom = network.stores.at["MNK-Res", "e_nom"]  # Total storage
        min_turbine2_eff = network.stores.at["MNK-Res", "min_turbine_eff"] # This is a new attribute to be added to csv file
        delta_turbine2_eff = 1 - min_turbine2_eff # Define Efficiency Range

        # Add the constraint 
        m.add_constraints(
            Link1_MWh
            <= ((Store1_level / Store1_e_nom * delta_turbine1_eff) + min_turbine1_eff) * Link1_p_nom,
            name="Turbine1_eff",
            )
        m.add_constraints(
            Link2_MWh
            <= ((Store2_level / Store2_e_nom * delta_turbine2_eff) + min_turbine2_eff) * Link2_p_nom,
            name="Turbine2_eff",
            )`

Error 

`C:\Users\User\AppData\Roaming\Python\Python39\site-packages\linopy\common.py:124: UserWarning: Coordinates across variables not equal. Perform outer join.
  warn(
Traceback (most recent call last):

  File "C:\Users\User\OneDrive\S(Pypsa)\2401_GMNK\Single-Yr_GMNK_v3.2.py", line 186, in <module>
    network=expansion('A(RSA-DC_M_P50)')

  File "C:\Users\User\OneDrive\S(Pypsa)\2401_GMNK\Single-Yr_GMNK_v3.2.py", line 165, in expansion
    network.optimize.solve_model(solver_name="cplex",

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\pypsa\optimization\optimize.py", line 616, in solve_model
    assign_duals(n, assign_all_duals)

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\pypsa\optimization\optimize.py", line 384, in assign_duals
    for name, dual in m.dual.items():

  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\linopy\model.py", line 189, in dual
    return self.constraints.dual

  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\linopy\constraints.py", line 626, in dual
    return save_join(*[v.dual.rename(k) for k, v in self.items()])

  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\linopy\common.py", line 131, in save_join
    return Dataset({ds.name: ds for ds in arrs})

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\xarray\core\dataset.py", line 696, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\xarray\core\dataset.py", line 425, in merge_data_and_coords
    return merge_core(

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\xarray\core\merge.py", line 720, in merge_core
    variables, out_indexes = merge_collected(

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\xarray\core\merge.py", line 290, in merge_collected
    merged_vars[name] = unique_variable(

  File "C:\Users\User\.conda\envs\pypsa-root\lib\site-packages\xarray\core\merge.py", line 144, in unique_variable
    raise MergeError(

MergeError: conflicting values for variable 'Link' on objects to be combined. You can skip this check by specifying compat='override'.

None`

**Comment by fneum** [comment]
I just tested this with the latest version (some changes in dimension names). The error seems to have disappeared. Please reopen if this is not the case.


```py
import pypsa
import pandas as pd

SNAPSHOTS = pd.date_range("2023-01-01 09:00", "2023-01-01 19:00", freq="H")

LOAD = {"name": "load_1",
    	"profile": pd.Series([40, 70, 60, 50, 10, 20, 40, 50, 50, 40, 40], index=SNAPSHOTS)}

GENERATORS = [{"name": "gas_1",
    			    "p_nom": 100,
                            "p_min" : 0,
       			     "marginal_cost": 10},
              {"name": "gas_2",
    			"p_nom": 100,
			"p_min" : 50,
       			"marginal_cost": 5}]


############
network = pypsa.Network()

network.set_snapshots(SNAPSHOTS)

main_bus = "bus_grid"
network.add("Bus", name=main_bus)

for gen in GENERATORS:
	network.add("Generator",
				name=gen["name"],
				bus=main_bus,
				committable=True,
				p_nom=gen["p_nom"],
				marginal_cost=gen["marginal_cost"],
			)

network.add("Load", 
			name=LOAD["name"],  
			bus=main_bus,  
			p_set=LOAD["profile"]) 

network_model = network.optimize.create_model()

# CONSTRAINT: Generator has min.power
for gen in GENERATORS:
        generator_power = network_model.variables['Generator-p'].sel(name=gen["name"])
        generator_status = network_model.variables['Generator-status'].sel(name=gen["name"])
        lhs = generator_power - generator_status * gen["p_min"]
        rhs = 0
        network_model.add_constraints(lhs >= rhs, name="Generator-p-min"+ "_" + gen["name"])


network.optimize.solve_model(solver_name="highs")   

```
